// IMPORTANT: Replace this file with the one generated by FlutterFire CLI
// Run: flutterfire configure
// See README.md for full setup instructions

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ⚠️ REPLACE ALL VALUES BELOW with your real Firebase config
  // Run: flutterfire configure  (after: dart pub global activate flutterfire_cli)

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAujs7r9m0tB4fAW4IXQGJUmXeysCHU_YU',
    appId: '1:17360985331:android:1c92d0319e061d7d536b86',
    messagingSenderId: '17360985331',
    projectId: 'taskmaster-81256',
    storageBucket: 'taskmaster-81256.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB37iXZJMjULBXOODcuEk4y0lunvly_By8',
    appId: '1:17360985331:ios:f71c9415b25e11c0536b86',
    messagingSenderId: '17360985331',
    projectId: 'taskmaster-81256',
    storageBucket: 'taskmaster-81256.firebasestorage.app',
    iosBundleId: 'com.taskmaster.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:YOUR_PROJECT_NUMBER:web:YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_PROJECT_NUMBER',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
  );
}